apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web
        image: myapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000

